export { default as aWeighting, coefs as aWeightingCoefs } from './a-weighting.js'
export { default as cWeighting, coefs as cWeightingCoefs } from './c-weighting.js'
export { default as kWeighting, coefs as kWeightingCoefs } from './k-weighting.js'
export { default as itu468, coefs as itu468Coefs } from './itu468.js'
export { default as riaa, coefs as riaaCoefs } from './riaa.js'
